# Generated by Django 4.2.16 on 2024-12-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_lname_user_login_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='passwd1',
            new_name='passwd',
        ),
    ]
